#line 2 "layerd_dpp_lexer_beta.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 159
#define YY_END_OF_BUFFER 160
static yyconst short int yy_acclist[694] =
    {   0,
      160,  158,  159,    7,  158,  159,    7,  159,   20,  158,
      159,  158,  159,  158,  159,   41,  158,  159,   38,  158,
      159,   25,  158,  159,    8,  158,  159,    9,  158,  159,
       36,  158,  159,   34,  158,  159,   15,  158,  159,   35,
      158,  159,   16,  158,  159,   37,  158,  159,  153,  155,
      158,  159,  153,  155,  158,  159,   24,  158,  159,   14,
      158,  159,   19,  158,  159,   17,  158,  159,   18,  158,
      159,   22,  158,  159,  157,  158,  159,  157,  158,  159,
       12,  158,  159,   13,  158,  159,   40,  158,  159,  157,
      158,  159,  157,  158,  159,  157,  158,  159,  157,  158,

      159,  157,  158,  159,  157,  158,  159,  157,  158,  159,
      157,  158,  159,  157,  158,  159,  157,  158,  159,  157,
      158,  159,  157,  158,  159,  157,  158,  159,  157,  158,
      159,  157,  158,  159,  157,  158,  159,  157,  158,  159,
      157,  158,  159,  157,  158,  159,   10,  158,  159,   39,
      158,  159,   11,  158,  159,   21,  158,  159,    1,    7,
      159,    7,   29,  152,  157,   52,   30,   49,   47,   32,
       45,   33,   46,   57,   59,    5,    6,   48,  153,  155,
      155,  153,  155,   23,   42,   27,   26,   56,   28,   43,
      157,  157,   51,  157,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  111,  157,  157,  157,  157,  157,  157,
      157,  157,   71,  157,  157,  108,  157,  157,   91,  157,
      157,  150,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,   50,   31,  151,   58,  156,
      154,  155,   53,   54,   44,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  144,  157,  157,  157,  157,  157,  157,
      112,  157,  101,  157,  157,  157,  157,  157,  157,  128,

      157,  157,  157,  157,  157,  157,   87,  157,  157,  157,
      157,  157,  157,   92,  157,  157,  157,  157,  157,  157,
      157,   94,  157,  157,  157,  157,  103,  157,  157,  157,
      157,  157,  157,  157,  157,  119,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  154,
       55,  157,  157,  157,  123,  157,  157,  131,  157,  115,
      157,  157,  138,  157,  157,  157,  157,  157,  157,  157,
      157,  109,  157,   64,  157,  149,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  129,  157,  157,  157,

        2,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,    3,  157,  142,  157,  133,  157,  157,  157,
      157,  157,  157,  157,  124,  157,  157,  157,  157,  154,
      157,  157,  143,  157,  105,  157,  120,  157,   63,  157,
       79,  157,  157,  157,  157,  157,  157,  157,  157,  157,
        4,  157,   86,  157,  135,  157,   82,  157,  157,  157,
      157,  157,  145,  157,  157,  157,   93,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  126,  157,  127,

      157,  157,  157,  157,  157,  157,  118,  157,  157,  134,
      157,   65,  157,  157,  157,   61,  157,  157,  157,  110,
      157,  157,  157,  157,  157,  157,  157,  157,  122,  157,
      136,  157,  157,   81,  157,  157,  157,  157,  157,  157,
       60,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  125,  157,  157,  157,  157,   90,  157,  157,
      157,  157,   72,  157,  157,  104,  157,  117,  157,  146,
      157,   78,  157,  140,  157,   97,  157,  114,  157,  147,
      157,  157,  132,  157,  157,  157,  157,  157,  157,  157,
      157,  137,  157,  116,  157,  157,   83,  157,  121,  157,

      113,  157,  148,  157,  157,   99,  157,  157,  157,  157,
      157,  157,   75,  157,   85,  157,  157,  157,  157,  157,
      157,   74,  157,  157,  157,  157,  157,   69,  157,  157,
      157,  157,  157,   89,  157,  106,  157,  157,  157,   67,
      157,  157,  157,   77,  157,  157,  157,  157,   98,  157,
       96,  157,   88,  157,  100,  157,  157,  102,  157,  130,
      157,   80,  157,  157,  139,  157,  157,   95,  157,  157,
      157,   66,  157,  157,   62,  157,  157,   73,  157,  107,
      157,  157,   68,  157,  157,   76,  157,   70,  157,  141,
      157,   84,  157

    } ;

static yyconst short int yy_accept[518] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   16,   19,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   53,   57,   60,   63,   66,
       69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  126,
      129,  132,  135,  138,  141,  144,  147,  150,  153,  156,
      159,  162,  163,  164,  164,  165,  165,  166,  167,  168,
      169,  169,  169,  170,  171,  172,  173,  174,  175,  176,
      177,  178,  179,  179,  179,  181,  182,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  192,  193,  194,

      195,  196,  197,  198,  199,  200,  201,  202,  203,  204,
      206,  207,  208,  209,  210,  211,  212,  213,  215,  216,
      218,  219,  221,  222,  224,  225,  226,  227,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  237,  238,  239,
      240,  241,  242,  243,  244,  245,  246,  247,  248,  249,
      250,  251,  252,  253,  254,  255,  256,  257,  258,  258,
      258,  259,  259,  259,  260,  261,  262,  262,  263,  264,
      265,  266,  267,  268,  269,  270,  271,  272,  273,  274,
      275,  276,  277,  278,  279,  280,  281,  282,  283,  284,
      286,  287,  288,  289,  290,  291,  293,  295,  296,  297,

      298,  299,  300,  302,  303,  304,  305,  306,  307,  309,
      310,  311,  312,  313,  314,  316,  317,  318,  319,  320,
      321,  322,  324,  325,  326,  327,  329,  330,  331,  332,
      333,  334,  335,  336,  338,  339,  340,  341,  342,  343,
      344,  345,  346,  347,  348,  349,  350,  350,  350,  350,
      351,  351,  352,  353,  354,  355,  357,  358,  360,  362,
      363,  365,  366,  367,  368,  369,  370,  371,  372,  374,
      376,  378,  379,  380,  381,  382,  383,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
      397,  399,  400,  401,  403,  404,  405,  406,  407,  408,

      409,  410,  411,  412,  413,  414,  415,  416,  417,  418,
      419,  420,  421,  422,  423,  425,  427,  429,  430,  431,
      432,  433,  434,  435,  437,  438,  439,  440,  440,  441,
      442,  443,  445,  447,  449,  451,  453,  454,  455,  456,
      457,  458,  459,  460,  461,  463,  465,  467,  469,  470,
      471,  472,  473,  475,  476,  477,  479,  480,  481,  482,
      483,  484,  485,  486,  487,  488,  489,  490,  491,  492,
      493,  494,  495,  496,  497,  498,  500,  502,  503,  504,
      505,  506,  507,  509,  510,  512,  514,  515,  516,  518,
      519,  520,  522,  523,  524,  525,  526,  527,  528,  529,

      531,  533,  534,  536,  537,  538,  539,  540,  541,  543,
      544,  545,  546,  547,  548,  549,  550,  551,  552,  553,
      555,  556,  557,  558,  560,  561,  562,  563,  565,  566,
      568,  570,  572,  574,  576,  578,  580,  582,  583,  585,
      586,  587,  588,  589,  590,  591,  592,  594,  596,  597,
      599,  601,  603,  605,  606,  608,  609,  610,  611,  612,
      613,  615,  617,  618,  619,  620,  621,  622,  624,  625,
      626,  627,  628,  630,  631,  632,  633,  634,  636,  638,
      639,  640,  642,  643,  644,  646,  647,  648,  649,  651,
      653,  655,  657,  658,  660,  662,  664,  665,  667,  668,

      670,  671,  672,  674,  675,  677,  678,  680,  682,  683,
      685,  686,  688,  690,  692,  694,  694
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   36,   37,   36,   36,   38,   39,   36,   36,   36,
       36,   36,   40,   36,   41,   36,   36,   42,   36,   36,
       43,   44,   45,   46,   36,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   36,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[522] =
    {   0,
        0,    0,    0,    0,  665,  664,  666,  669,   74,   77,
      639,   76,    0,  638,   74,  619,  669,  669,  636,   70,
      669,   71,  648,   73,  115,   82,  637,  669,   64,   66,
       68,  669,  619,    0,  669,  669,  632,  609,   43,   56,
       51,   47,   64,  605,   79,  604,  593,  111,   97,   81,
      602,  128,   98,  130,   54,   64,  669,   82,  669,  669,
      167,  195,  669,   79,  669,  181,    0,  669,  669,  669,
      642,  199,  669,  669,  669,  669,  669,  638,  669,  669,
      669,  669,    0,  191,  180,  669,  216,  669,    0,  669,
      624,  669,  669,  669,  669,  103,    0,  617,  669,  584,

      586,  585,  594,  579,  139,  596,  595,  581,  165,  574,
      575,  572,  127,   84,  577,  575,  572,    0,  569,    0,
      571,  206,  158,    0,  562,  571,  571,  561,  568,  569,
      570,  574,  574,  558,  571,  558,   85,  572,  193,  549,
      553,  556,  545,  168,  560,  551,  182,  551,  552,  550,
      152,  172,  547,  184,  554,  553,  669,  669,  249,  255,
      669,  262,  267,  669,    0,  281,  270,  332,  669,  669,
      581,  569,  540,  555,  545,  555,  550,  549,  550,  535,
      533,  201,  541,  548,  543,  545,  541,  532,  541,    0,
      538,  523,  523,  539,  538,  157,  519,  236,  524,  531,

      530,  514,  528,  173,  530,  509,  523,  524,    0,  507,
      515,  521,  508,  515,    0,  506,  521,  500,  233,  508,
      515,    0,  498,  497,  497,    0,  498,  509,  494,  218,
      493,  496,  505,    0,  504,  489,  493,  491,  496,  489,
      489,  483,  497,  499,  487,  479,  290,  273,  308,  669,
      322,  669,  506,  479,  484,    0,  483,    0,    0,  485,
        0,  474,  472,  481,  476,  468,  468,  474,    0,    0,
        0,  244,  470,  479,  471,  463,  476,  479,  455,  473,
      460,  471,  452,  457,  454,  455,  450,  451,  457,  453,
        0,  449,  457,    0,  462,  463,  449,  445,  448,  459,

      454,  453,  448,  441,  442,  437,  448,  433,  436,  441,
      435,  445,  444,  424,    0,  430,    0,  437,  429,  435,
      424,  433,  419,    0,  419,  432,  431,  326,  336,  273,
      434,    0,    0,    0,    0,    0,  420,  432,  420,  426,
      425,  411,  414,  410,    0,  414,    0,    0,  422,  408,
      410,  403,    0,  416,  411,    0,  128,  418,  413,  408,
      399,  399,  397,  394,  393,  410,  401,  391,  389,  390,
      403,  402,  390,  398,  388,    0,    0,  395,  397,  392,
      379,  389,    0,  390,    0,    0,  381,  375,    0,  392,
      383,    0,  388,  382,  370,  385,  367,  374,  366,    0,

        0,  375,    0,  359,  358,  373,  375,  374,    0,  361,
      358,  373,  374,  347,  362,  354,  350,  352,  333,    0,
      336,  333,  345,    0,  343,  328,  327,    0,  332,    0,
        0,    0,    0,    0,    0,    0,    0,  338,    0,  330,
      328,  324,  336,  318,  315,  328,    0,    0,  317,    0,
        0,    0,    0,  317,    0,  312,  310,  324,  321,  304,
        0,    0,  319,  300,  301,  293,  311,    0,  291,  309,
      289,  299,    0,  288,  287,  272,  275,    0,    0,  266,
      260,    0,  269,  271,    0,  270,  268,  265,    0,    0,
        0,    0,  258,    0,    0,    0,  255,    0,  225,    0,

      216,  211,    0,  213,    0,  196,    0,    0,  197,    0,
      144,    0,    0,    0,    0,  669,  401,  403,  409,  412,
      415
    } ;

static yyconst short int yy_def[522] =
    {   0,
      516,    1,    1,    1,    1,    1,  516,  516,  516,  516,
      516,  517,  518,  516,  516,  519,  516,  516,  516,  516,
      516,  516,  516,  516,  516,   25,  516,  516,  516,  516,
      516,  516,  520,  520,  516,  516,  516,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  516,  516,  516,  516,
      516,  516,  516,  517,  516,  516,  520,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  521,  516,   25,  516,  516,  516,  521,  516,
      516,  516,  516,  516,  516,  516,  520,  520,  516,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  516,  516,  517,  517,
      516,  516,  516,  516,  521,  516,  516,  516,  516,  516,
      516,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  517,  517,  516,  516,
      516,  516,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  516,  166,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,    0,  516,  516,  516,  516,
      516
    } ;

static yyconst short int yy_nxt[745] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   13,   33,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   35,    8,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   34,   45,   34,   46,   47,   34,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   34,   34,
       34,   57,   58,   59,   60,   62,   62,   62,   62,   62,
       62,   65,   69,   74,   65,   80,   76,  516,   91,   92,
       81,   93,   94,   95,   96,   75,   77,   78,   82,   70,

      101,  109,  105,  102,  111,  103,  112,  157,  153,  106,
      114,  110,  104,  107,  154,  113,  108,  155,  115,   66,
       83,  116,   66,   86,  117,  118,  156,  136,  170,  171,
      120,   84,  192,   85,   85,   85,   85,  121,  122,  218,
      123,  193,  124,  137,  131,  219,  138,   86,   87,   86,
       86,  146,   88,   86,  158,   88,   89,  127,  132,  133,
      147,  128,  134,  135,   86,   87,   86,  148,   62,   62,
       62,  129,   88,   86,  412,  140,  130,  189,  141,  413,
       88,  142,  143,   89,  149,  516,   64,  150,  190,  151,
       64,  191,  144,  152,  515,  145,   62,   62,   62,  159,

      159,  160,  178,  179,   71,  277,  238,  278,   71,  166,
      166,  166,  166,  183,  229,  239,  184,  162,  162,  163,
      204,   86,  185,  205,   64,  240,  241,  287,   64,  167,
      230,  167,   64,  288,  168,  168,  168,  168,  243,  221,
       64,  244,   71,   64,  222,   64,   71,  233,   86,  514,
       71,  234,  199,  513,   65,  200,  223,  224,   71,  201,
       65,   71,  512,   71,  263,  264,  202,  247,  247,  247,
      203,  161,  311,  248,  248,  248,  161,  511,   65,  510,
      249,  249,  249,  312,  509,   71,   71,   71,  168,  168,
      168,  168,   66,  280,  301,   65,  281,  302,   66,  166,

      166,  166,  166,  342,  394,  508,  343,  507,  248,  248,
      248,  506,  395,  250,  251,  250,   66,  161,  505,  250,
      504,  503,  250,  502,  501,  500,   71,   71,   71,  499,
      250,  251,  250,   66,  498,  328,  497,  328,  496,  250,
      329,  329,  329,  329,  329,  329,  329,  329,  495,  250,
      168,  168,  168,  168,  329,  329,  329,  329,  494,  493,
      492,  491,  490,  489,   86,  488,   86,  487,  486,  516,
       86,  485,  484,   86,  483,  482,  481,  480,  479,  478,
      477,   86,  476,   86,  475,  474,  516,  473,  472,  471,
       86,  470,  469,  468,  467,  466,  465,  464,  463,  462,

       86,   64,  461,   64,   64,   64,   64,   67,   67,   71,
      460,  459,   71,   71,   71,   97,   97,   97,  165,  165,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,

      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  310,  309,
      308,  307,  306,  305,  304,  303,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  286,  285,
      284,  283,  282,  279,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  262,  261,  260,  259,

      258,  257,  256,  255,  254,  253,  252,  246,  245,  242,
      237,  236,  235,  232,  231,  228,  227,  226,  225,  220,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  198,  197,  196,  195,  194,  188,  187,  186,
      182,  181,  180,  177,  176,  175,  174,  173,  172,  169,
      164,  161,  139,  126,  125,  119,  100,   99,   98,   90,
       79,   73,   72,   68,   63,  516,   61,   61,    7,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516
    } ;

static yyconst short int yy_chk[745] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,    9,    9,   10,   10,
       10,   12,   15,   20,   64,   24,   22,   26,   29,   29,
       24,   30,   30,   31,   31,   20,   22,   22,   24,   15,

       39,   41,   40,   39,   42,   39,   42,   58,   55,   40,
       43,   41,   39,   40,   55,   42,   40,   56,   43,   12,
       25,   43,   64,   26,   43,   43,   56,   50,   96,   96,
       45,   25,  114,   25,   25,   25,   25,   45,   45,  137,
       45,  114,   45,   50,   49,  137,   50,   25,   25,   25,
       26,   53,   25,   25,   58,   25,   25,   48,   49,   49,
       53,   48,   49,   49,   25,   25,   25,   53,   61,   61,
       61,   48,   25,   25,  357,   52,   48,  113,   52,  357,
       25,   52,   52,   25,   54,   85,   66,   54,  113,   54,
       66,  113,   52,   54,  511,   52,   62,   62,   62,   66,

       66,   66,  105,  105,   72,  196,  151,  196,   72,   84,
       84,   84,   84,  109,  144,  151,  109,   72,   72,   72,
      123,   85,  109,  123,   66,  152,  152,  204,   66,   87,
      144,   87,   66,  204,   87,   87,   87,   87,  154,  139,
       66,  154,   72,   66,  139,   66,   72,  147,   85,  509,
       72,  147,  122,  506,  159,  122,  139,  139,   72,  122,
      160,   72,  504,   72,  182,  182,  122,  159,  159,  159,
      122,  162,  230,  160,  160,  160,  163,  502,  248,  501,
      162,  162,  162,  230,  499,  163,  163,  163,  167,  167,
      167,  167,  159,  198,  219,  247,  198,  219,  160,  166,

      166,  166,  166,  272,  330,  497,  272,  493,  247,  247,
      247,  488,  330,  166,  166,  166,  248,  249,  487,  166,
      486,  484,  166,  483,  481,  480,  249,  249,  249,  477,
      166,  166,  166,  247,  476,  251,  475,  251,  474,  166,
      251,  251,  251,  251,  328,  328,  328,  328,  472,  166,
      168,  168,  168,  168,  329,  329,  329,  329,  471,  470,
      469,  467,  466,  465,  168,  464,  168,  463,  460,  329,
      168,  459,  458,  168,  457,  456,  454,  449,  446,  445,
      444,  168,  443,  168,  442,  441,  329,  440,  438,  429,
      168,  427,  426,  425,  423,  422,  421,  419,  418,  417,

      168,  517,  416,  517,  517,  517,  517,  518,  518,  519,
      415,  414,  519,  519,  519,  520,  520,  520,  521,  521,
      413,  412,  411,  410,  408,  407,  406,  405,  404,  402,
      399,  398,  397,  396,  395,  394,  393,  391,  390,  388,
      387,  384,  382,  381,  380,  379,  378,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  355,  354,  352,  351,  350,
      349,  346,  344,  343,  342,  341,  340,  339,  338,  337,
      331,  327,  326,  325,  323,  322,  321,  320,  319,  318,
      316,  314,  313,  312,  311,  310,  309,  308,  307,  306,

      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  293,  292,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  268,  267,  266,  265,  264,  263,  262,  260,  257,
      255,  254,  253,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  233,  232,  231,  229,  228,
      227,  225,  224,  223,  221,  220,  218,  217,  216,  214,
      213,  212,  211,  210,  208,  207,  206,  205,  203,  202,
      201,  200,  199,  197,  195,  194,  193,  192,  191,  189,
      188,  187,  186,  185,  184,  183,  181,  180,  179,  178,

      177,  176,  175,  174,  173,  172,  171,  156,  155,  153,
      150,  149,  148,  146,  145,  143,  142,  141,  140,  138,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  121,  119,  117,  116,  115,  112,  111,  110,
      108,  107,  106,  104,  103,  102,  101,  100,   98,   91,
       78,   71,   51,   47,   46,   44,   38,   37,   33,   27,
       23,   19,   16,   14,   11,    7,    6,    5,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "layerd_dpp_lexer_beta.l"
#define INITIAL 0
#line 2 "layerd_dpp_lexer_beta.l"
/*-
 * Copyright (c) 2008 Alexis Ferreyra
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of copyright holders nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL COPYRIGHT HOLDERS OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/****************************************************************************
  layerd_dpp_parser_beta.l

  Scanner for Meta D++ Compiler

  This file must be processed with flex.

  Original Author: Alexis Ferreyra
  Contact: alexis.ferreyra@layerd.net
  
  Please visit http://layerd.net to get the last version
  of the software and information about LayerD technology.

****************************************************************************/
#include <iostream>
#include <wchar.h>
#ifdef WIN32
#include "..\\CodeDOM\\CDOM_IncludeAll.h"
#else
#include "../CodeDOM/CDOM_IncludeAll.h"
#endif
#include "layerd_dpp_parser_beta_tab.h"

#define LEXER_RETURN( N ) counter=0;yyposn=yylineno;return N;
#define LEXER_RETURN_VAL( N ) counter=0;yyposn=yylineno;return N;
#define CHAR_TYPE char
#define STR_CPY(N,M) wcscpy (N,M)
#define CONVERT_TO_DOM_CHAR(N) Convert_To_wchar(N)
#define CONVERT_TO_DOM_CHAR_XMLENCODED(N) Convert_To_wchar_XmlEncoded(N)

/* Definiciones para el control de posicion en BtYacc */
#define YYPOSN int
extern YYPOSN yyposn;

const CHAR_TYPE* GetLexerText();

wchar_t *wcharbuffer=NULL;
int current_wcharbuffer_lenght=0;
const wchar_t* Convert_To_wchar(const char* text);
const wchar_t* Convert_To_wchar_XmlEncoded(const char* text);
CodeDOM::XplDocumentation* CreateDocumentNode(const char* text);
#define COMMENT_BUFFER 64000
char lastCommentBuffer[COMMENT_BUFFER];
bool lastCommentValid = false;
int counter=0;

/*/////////////////////////////////////////////////////////////////////////////
// declarations section*/
#define YY_NEVER_INTERACTIVE 1
#define COMMENT 1

#define COMILLA 2

#line 874 "layerd_dpp_lexer_beta.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 88 "layerd_dpp_lexer_beta.l"


 /*/////////////////////////////////////////////////////////////////////////////
 // rules section*/


 /*	STRING LITERAL (DEBE ESTAR PRIMERO)	*/
#line 1033 "layerd_dpp_lexer_beta.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 517 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 669 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 95 "layerd_dpp_lexer_beta.l"
{LEXER_RETURN(ERROR_COMILLA);BEGIN(0);}
	YY_BREAK
/*	LITERALES NULL Y BOOLEAN */
case 2:
YY_RULE_SETUP
#line 98 "layerd_dpp_lexer_beta.l"
{//NULL_LITERAL
								yylval.literal=new CodeDOM::XplLiteral();
								yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_NULL);
								yylval.literal->set_str(DT("0"));
								yyposn=yylineno;
								LEXER_RETURN(NULL_LITERAL);
							}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "layerd_dpp_lexer_beta.l"
{//BOOLEAN_LITERAL_TRUE
								yylval.literal=new CodeDOM::XplLiteral();
								yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_BOOL);
								yylval.literal->set_str(DT("true"));
								yyposn=yylineno;
								LEXER_RETURN(BOOLEAN_LITERAL_TRUE);
							}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "layerd_dpp_lexer_beta.l"
{//BOOLEAN_LITERAL_FALSE
								yylval.literal=new CodeDOM::XplLiteral();
								yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_BOOL);
								yylval.literal->set_str(DT("false"));
								yyposn=yylineno;
								LEXER_RETURN(BOOLEAN_LITERAL_FALSE);
							}
	YY_BREAK
/*	COMENTARIOS	*/
case 5:
YY_RULE_SETUP
#line 123 "layerd_dpp_lexer_beta.l"
{
                register int c;
                for ( ; ; ){
					while ( (c = yyinput()) != '*' &&
						c != EOF ){
						/* eat up text of comment */
						if(counter<COMMENT_BUFFER+5){
							switch(c){
								case '\"':
									lastCommentBuffer[counter]='&';
									lastCommentBuffer[counter+1]='q';
									lastCommentBuffer[counter+2]='u';
									lastCommentBuffer[counter+3]='o';
									lastCommentBuffer[counter+4]='t';
									lastCommentBuffer[counter+5]=';';
									counter+=6;
									break;
								case '&':
									lastCommentBuffer[counter]='&';
									lastCommentBuffer[counter+1]='a';
									lastCommentBuffer[counter+2]='m';
									lastCommentBuffer[counter+3]='p';
									lastCommentBuffer[counter+4]=';';
									counter+=5;
									break;
								case '<':
									lastCommentBuffer[counter]='&';
									lastCommentBuffer[counter+1]='l';
									lastCommentBuffer[counter+2]='t';
									lastCommentBuffer[counter+3]=';';
									counter+=4;
									break;
								case '>':
									lastCommentBuffer[counter]='&';
									lastCommentBuffer[counter+1]='g';
									lastCommentBuffer[counter+2]='t';
									lastCommentBuffer[counter+3]=';';
									counter+=4;
									break;
								default:
									lastCommentBuffer[counter]=c;
									counter++;
							}
						}
					}
					if ( c == '*' )
						{
						while ( (c = yyinput()) == '*' )
							;
						if ( c == '/' )
							break;    /* found the end */
						}
					if ( c == EOF )
						{
							//yyerror( "EOF in comment" );
							break;
						}
                }
				lastCommentBuffer[counter]=0;
				lastCommentValid = true;
				//Agregado para incluir comentarios como tokens
				CodeDOM::XplDocumentation* doc = CreateDocumentNode(lastCommentBuffer);
				yylval.node = doc;
				LEXER_RETURN_VAL(COMENTARIO);
            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 190 "layerd_dpp_lexer_beta.l"
{
					register int c;
					bool ignoreBarra=true;
					if(counter!=0){
						lastCommentBuffer[counter]='\n';
						counter++;
					}
					while ( true ){
						c = yyinput();
						if(counter<COMMENT_BUFFER+5 && c!='\n'){
							if(!(ignoreBarra && c=='/')){
								ignoreBarra=false;
								switch(c){
									case '\"':
										lastCommentBuffer[counter]='&';
										lastCommentBuffer[counter+1]='q';
										lastCommentBuffer[counter+2]='u';
										lastCommentBuffer[counter+3]='o';
										lastCommentBuffer[counter+4]='t';
										lastCommentBuffer[counter+5]=';';
										counter+=6;
										break;
									case '&':
										lastCommentBuffer[counter]='&';
										lastCommentBuffer[counter+1]='a';
										lastCommentBuffer[counter+2]='m';
										lastCommentBuffer[counter+3]='p';
										lastCommentBuffer[counter+4]=';';
										counter+=5;
										break;
									case '<':
										lastCommentBuffer[counter]='&';
										lastCommentBuffer[counter+1]='l';
										lastCommentBuffer[counter+2]='t';
										lastCommentBuffer[counter+3]=';';
										counter+=4;
										break;
									case '>':
										lastCommentBuffer[counter]='&';
										lastCommentBuffer[counter+1]='g';
										lastCommentBuffer[counter+2]='t';
										lastCommentBuffer[counter+3]=';';
										counter+=4;
										break;
									default:
										lastCommentBuffer[counter]=c;
										counter++;
								}
							}
						}
						if(c=='\n'){
							lastCommentBuffer[counter]='\n';
							counter++;
							break;
						}
					}
					lastCommentBuffer[counter] = 0;
					lastCommentValid = true;
					//Agregado para incluir comentarios como tokens
					CodeDOM::XplDocumentation* doc = CreateDocumentNode(lastCommentBuffer);
					yylval.node = doc;
					LEXER_RETURN_VAL(COMENTARIO);
				}
	YY_BREAK
/* ESPACIO EN BLANCO */
case 7:
YY_RULE_SETUP
#line 256 "layerd_dpp_lexer_beta.l"
;//LEXER_RETURN(WHITE_SPACE);
	YY_BREAK
/* SEPARADORES O PUNCTUATORS */
case 8:
YY_RULE_SETUP
#line 261 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OPEN_PARENTESIS);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 262 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(CLOSE_PARENTESIS);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 263 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OPEN_LLAVE);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 264 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(CLOSE_LLAVE);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 265 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OPEN_CORCHETE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 266 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(CLOSE_CORCHETE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 267 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PUNTO_COMA);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 268 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(COMA);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 269 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PUNTO);
	YY_BREAK
/* OPERADORES */
case 17:
YY_RULE_SETUP
#line 273 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_IGUAL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 274 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MAYOR);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 275 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 276 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_ADMIRACION);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 277 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_CELDILLA);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 278 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_PREGUNTA);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 279 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_DOSPUNTOSDOBLE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 280 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_DOSPUNTOS);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 281 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_COMILLA);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 282 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_IGUALIGUAL);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 284 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENORIGUAL);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 285 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MAYORIGUAL);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 286 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_ADMIRACIONIGUAL);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 287 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_YY);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 288 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_OO);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 289 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MASMAS);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 290 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOSMENOS);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 291 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MAS);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 292 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOS);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 293 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_ASTERISCO);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 294 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_DIVIDIDO);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 295 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_Y);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 296 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_O);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 297 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SOMBRERO);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 298 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_PORCENTAJE);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 299 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTLEFT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 300 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTRIGHT);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 301 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTRIGHT_JAVA);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 302 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MASIGUAL);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 303 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOSIGUAL);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 304 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_ASTERISCOIGUAL);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 305 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_DIVIDIDOIGUAL);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 306 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_YIGUAL);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 307 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_OIGUAL);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 308 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SOMBREROIGUAL);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 309 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_PORCENTAJEIGUAL);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 310 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTLEFTIGUAL);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 311 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTRIGHTIGUAL);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 312 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_SHIFTRIGHT_JAVA_IGUAL);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 313 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_IGUALMAYOR);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 314 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOSMAYOR);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 315 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_MENOSMAYORASTERISCO);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 316 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(OP_PUNTOASTERISCO);
	YY_BREAK
/*	PALABRAS CLAVE */
case 60:
YY_RULE_SETUP
#line 321 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IMPORT);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 322 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_USING);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 323 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_NAMESPACE);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 324 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CLASS);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 325 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ENUM);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 326 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_UNION);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 327 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INTERFACE);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 328 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INHERITS);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 329 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IMPLEMENTS);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 330 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_VIRTUAL);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 331 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_NONVIRTUAL);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 332 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FPOINTER);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 334 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_PUBLIC);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 335 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_PROTECTED);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 336 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_PRIVATE);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 337 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IPUBLIC);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 338 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IPROTECTED);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 339 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IPRIVATE);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 341 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_STATIC);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 342 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CONST);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 343 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_VOLATILE);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 344 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_EXTERN);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 346 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FORCE);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 347 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FACTORY);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 348 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INTERACTIVE);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 349 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_KEYWORD);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 351 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FINAL);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 352 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_NEW);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 353 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_OVERRIDE);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 354 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ABSTRACT);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 355 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_PARAMS);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 356 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IN);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 357 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_OUT);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 358 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INOUT);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 359 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_REF);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 360 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_EXTENSION);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 361 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ORDINARY);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 362 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_STRUCT);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 363 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_OPERATOR);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 364 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INDEXER);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 365 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_PROPERTY);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 366 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_GET);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 368 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_READONLY);
	YY_BREAK
/*"blocktofactorys"			LEXER_RETURN(PC_BLOCKTOFACTORYS);*/
/*"except"					LEXER_RETURN(PC_EXCEPT);*/
case 103:
YY_RULE_SETUP
#line 371 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_SET);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 372 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_RESUME);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 373 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_BREAK);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 374 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CONTINUE);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 375 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_WRITECODE);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 376 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IF);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 377 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ELSE);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 378 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_WHILE);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 379 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_DO);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 380 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FOR);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 381 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FOR);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 382 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_SWITCH);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 383 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CASE);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 384 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_DEFAULT);
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 385 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_RETURN);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 386 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_THROW);
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 387 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_TRY);
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 388 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CATCH);
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 389 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FINALLY);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 390 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_DELETE);
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 391 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_BOOL);
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 392 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_VOID);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 393 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_OBJECT);
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 394 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_SBYTE);
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 395 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_SHORT);
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 396 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INT);
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 397 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_LONG);
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 398 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_UNSIGNED);
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 399 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_BYTE);
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 400 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_USHORT);
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 401 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_UINT);
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 402 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ULONG);
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 403 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_FLOAT);
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 404 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_DOUBLE);
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 405 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_DECIMAL);
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 406 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_CHAR);
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 407 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ASCII_CHAR);
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 408 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_STRING);
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 409 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_ASCII_STRING);
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 410 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_TYPE);
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 411 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_BLOCK);
	YY_BREAK
/*"expression"				LEXER_RETURN(PC_EXPRESSION);*/
case 144:
YY_RULE_SETUP
#line 413 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_EXPRESSION);
	YY_BREAK
/*"expressionlist"			LEXER_RETURN(PC_EXPRESSIONLIST);*/
case 145:
YY_RULE_SETUP
#line 415 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_INAME);
	YY_BREAK
/*"statement"					LEXER_RETURN(PC_STATEMENT);*/
case 146:
YY_RULE_SETUP
#line 417 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_SIZEOF);
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 418 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_TYPEOF);
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 419 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_GETTYPE);
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 420 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_EXEC);
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 421 "layerd_dpp_lexer_beta.l"
LEXER_RETURN(PC_IS);
	YY_BREAK
/*	STRING LITERALS	*/
case 151:
YY_RULE_SETUP
#line 425 "layerd_dpp_lexer_beta.l"
{//CHAR_LITERAL
								yylval.literal=new CodeDOM::XplLiteral();
								yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_CHAR);
								yylval.literal->set_str(CONVERT_TO_DOM_CHAR_XMLENCODED(GetLexerText()));
								yyposn=yylineno;
								LEXER_RETURN_VAL(CHARACTER_LITERAL);
							}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 434 "layerd_dpp_lexer_beta.l"
{//STRING_LITERAL
							yylval.literal=new CodeDOM::XplLiteral();
							yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_STRING);
							yylval.literal->set_str(CONVERT_TO_DOM_CHAR_XMLENCODED(GetLexerText()));
							yyposn=yylineno;
							LEXER_RETURN_VAL(STRING_LITERAL);
		                }
	YY_BREAK
/*	LITERALES NUMERICAS */
case 153:
YY_RULE_SETUP
#line 444 "layerd_dpp_lexer_beta.l"
{//INTEGER_LITERAL
									yylval.literal=new CodeDOM::XplLiteral();
									yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_INTEGER);
									yylval.literal->set_str(CONVERT_TO_DOM_CHAR(GetLexerText()));
    								yyposn=yylineno;
									LEXER_RETURN_VAL(INTEGER_LITERAL);
							}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 452 "layerd_dpp_lexer_beta.l"
{//REAL_LITERAL
									yylval.literal=new CodeDOM::XplLiteral();
									yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_REAL);
									yylval.literal->set_str(CONVERT_TO_DOM_CHAR(GetLexerText()));
    								yyposn=yylineno;
									LEXER_RETURN_VAL(FLOAT_LITERAL);
							}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 460 "layerd_dpp_lexer_beta.l"
{//REAL_LITERAL
									yylval.literal=new CodeDOM::XplLiteral();
									yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_REAL);
									yylval.literal->set_str(CONVERT_TO_DOM_CHAR(GetLexerText()));
    								yyposn=yylineno;
									LEXER_RETURN_VAL(FLOAT_LITERAL);
							}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 468 "layerd_dpp_lexer_beta.l"
{//HEX_LITERAL
									yylval.literal=new CodeDOM::XplLiteral();
									yylval.literal->set_type(CodeDOM::ZOELITERALTYPE_ENUM_HEX);
									yylval.literal->set_str(CONVERT_TO_DOM_CHAR(GetLexerText()));
    								yyposn=yylineno;
									LEXER_RETURN_VAL(INTEGER_LITERAL);
							}
	YY_BREAK
/*	IDENTIFICADORES	*/
case 157:
YY_RULE_SETUP
#line 477 "layerd_dpp_lexer_beta.l"
{//IDENTIFICADORES
								if(YY_START!=0){
									switch(YY_START){
										case COMILLA:
											LEXER_RETURN_VAL(ERROR_COMILLA);BEGIN(0);
											break;
										default:
											LEXER_RETURN_VAL(ERROR_LEXICO);BEGIN(0);
									};
								}
								else {
									if(GetLexerText()[0]=='@')
										STR_CPY(yylval.str,CONVERT_TO_DOM_CHAR(GetLexerText()+1));
									else
										STR_CPY(yylval.str,CONVERT_TO_DOM_CHAR(GetLexerText()));
    								yyposn=yylineno;
									LEXER_RETURN_VAL(IDENTIFICADOR);
								}
							}
	YY_BREAK
/*	CAULQUIER OTRO CARACTER ES UN ERROR	*/
case 158:
YY_RULE_SETUP
#line 498 "layerd_dpp_lexer_beta.l"
{LEXER_RETURN(MAL_CARACTER);BEGIN(0);}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 500 "layerd_dpp_lexer_beta.l"
ECHO;
	YY_BREAK
#line 2132 "layerd_dpp_lexer_beta.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(COMILLA):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 517 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 517 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 516);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 500 "layerd_dpp_lexer_beta.l"



/*/////////////////////////////////////////////////////////////////////////////
// Rutinas Basicas */

int yywrap(){
  return -1;
}

CodeDOM::XplDocumentation* CreateDocumentNode(const char* text){
	CodeDOM::XplDocumentation* document = new CodeDOM::XplDocumentation();
	document->set_ElementName(L"documentation");
	document->set_short( Convert_To_wchar(text) );
	return document;
}

const CHAR_TYPE* GetLexerText(){
	if(yytext[0]=='\"' || yytext[0]=='\''){
		yytext[yyleng-1]='\0';
		return yytext+1;
	}
	else{
		return yytext;
	}
}

const wchar_t* Convert_To_wchar(const char* text){
  int length = strlen(text);
  if(wcharbuffer==NULL || current_wcharbuffer_lenght<length){
      //Asigno memoria al buffer temporal
      wcharbuffer = new wchar_t[length+1];
  }
  mbstowcs(wcharbuffer,text,length);
  wcharbuffer[length]=L'\0';
  return wcharbuffer;
}

void move_chars(wchar_t* wcharbuffer,int from, int to, int offset){
	for(;to>=from;to--)
		wcharbuffer[to+offset]=wcharbuffer[to];
}
void my_strcpy(wchar_t*target, wchar_t*source){
	int max=wcslen(source)-1;
	for(;max>-1;max--)
		target[max]=source[max];
}
const wchar_t* Convert_To_wchar_XmlEncoded(const char* text){
  //Primero cuento los caracteres a convertir: " < > &
  int count=0;
  for(int n=0;n<strlen(text);n++){
    if(text[n]=='\"')count+=5;
    else if(text[n]=='&')count+=4;
    else if(text[n]=='<')count+=3;
    else if(text[n]=='>')count+=3;
  }

  if(count==0)return Convert_To_wchar(text);
  //Almaceno el buffer
  if(wcharbuffer==NULL || current_wcharbuffer_lenght<yyleng+count){
      //Asigno memoria al buffer temporal
      wcharbuffer=new wchar_t[yyleng+count+1];
  }
  mbstowcs(wcharbuffer,text,yyleng);
  wcharbuffer[yyleng]=L'\0';
  count=0;
  for(int n=0;wcharbuffer[n]!=0;n++){
    if(wcharbuffer[n]=='\"'){
        //Primero muevo la cadena y luego inserto
		move_chars(wcharbuffer,n+1,yyleng+count,5);
        my_strcpy(&wcharbuffer[n],L"&quot;");
		count+=5;n+=5;
    }
    else if(wcharbuffer[n]=='&'){
        //Primero muevo la cadena y luego inserto
		move_chars(wcharbuffer,n+1,yyleng+count,4);
        my_strcpy(&wcharbuffer[n],L"&amp;");
		count+=4;n+=4;
    }
    else if(wcharbuffer[n]=='<'){
        //Primero muevo la cadena y luego inserto
		move_chars(wcharbuffer,n+1,yyleng+count,3);
		my_strcpy(&wcharbuffer[n],L"&lt;");
		count+=3;n+=3;
    }
    else if(wcharbuffer[n]=='>'){
        //Primero muevo la cadena y luego inserto
		move_chars(wcharbuffer,n+1,yyleng+count,3);
        my_strcpy(&wcharbuffer[n],L"&gt;");
		count+=3;n+=3;
    }
  }

  return wcharbuffer;
}
