/*-------------------------------------------------
 *
 *	Este archivo fue generado automáticamente.
 *	Fecha: 09/04/2009 17:21:32
 *
 *	Generado por Zoe CodeDOM Generator.
 *	COPYRIGHT 2002. por Alexis Ferreyra.
 *
 *------------------------------------------------*/

#ifndef __LAYERD_CODEDOM_SIMPLETYPES_V1_0
#define __LAYERD_CODEDOM_SIMPLETYPES_V1_0
#include "CDOMBase.h"

namespace CodeDOM{

enum CodeDOMTypes {
	CODEDOMTYPES_ZOENODELIST = 1000, 
	CODEDOMTYPES_EMPTY = 0, 
	CODEDOMTYPES_ZOENODE = 1, 
	CODEDOMTYPES_STRING = 2, 
	CODEDOMTYPES_INTEGER = 3, 
	CODEDOMTYPES_UNSIGNED = 4, 
	CODEDOMTYPES_DATETIME = 5, 
	CODEDOMTYPES_BOOLEAN = 6, 
	CODEDOMTYPES_ZOEEXTENDEDLAYERDZOEREQUIREMENTSCONFIG = 100, 
	CODEDOMTYPES_ZOECASTEXPRESSION = 101, 
	CODEDOMTYPES_ZOEOUTPUTMODULECAPABILITIES = 102, 
	CODEDOMTYPES_ZOECLASSMEMBERSLIST = 103, 
	CODEDOMTYPES_ZOECASE = 104, 
	CODEDOMTYPES_ZOEWRITECODEBODY = 105, 
	CODEDOMTYPES_ZOEINHERITS = 106, 
	CODEDOMTYPES_ZOETARGETPLATFORM = 107, 
	CODEDOMTYPES_ZOEDOCUMENT = 108, 
	CODEDOMTYPES_ZOEFUNCTIONBODY = 109, 
	CODEDOMTYPES_ZOECATCHSTATEMENT = 110, 
	CODEDOMTYPES_ZOETYPE = 111, 
	CODEDOMTYPES_ZOEPLATFORM = 112, 
	CODEDOMTYPES_ZOESOURCEFILE = 113, 
	CODEDOMTYPES_ZOEEXPRESSIONLIST = 114, 
	CODEDOMTYPES_ZOEASSING = 115, 
	CODEDOMTYPES_ZOETERNARYOPERATOR = 116, 
	CODEDOMTYPES_ZOEPARAMETER = 117, 
	CODEDOMTYPES_ZOECATCHINIT = 118, 
	CODEDOMTYPES_ZOEPLATFORMALIAS = 119, 
	CODEDOMTYPES_FACTORYTYPESDATABASE = 120, 
	CODEDOMTYPES_ZOEPROPERTY = 121, 
	CODEDOMTYPES_ZOEDECLARATOR = 122, 
	CODEDOMTYPES_ZOEFILEDATA = 123, 
	CODEDOMTYPES_ZOECEXPRESSION = 124, 
	CODEDOMTYPES_ZOENAME = 125, 
	CODEDOMTYPES_ZOEPOINTERINFO = 126, 
	CODEDOMTYPES_ZOESWITCHSTATEMENT = 127, 
	CODEDOMTYPES_ZOECLASSFACTORYSPERMISSIONS = 128, 
	CODEDOMTYPES_ZOEPARAMETERS = 129, 
	CODEDOMTYPES_ZOELAYERDZOEPROGRAMREQUIREMENTS = 130, 
	CODEDOMTYPES_ZOEAUTOINSTANCE = 131, 
	CODEDOMTYPES_ZOELAYERDZOEDOCUMENTCONFIG = 132, 
	CODEDOMTYPES_ZOESETPLATFORMS = 133, 
	CODEDOMTYPES_ZOEFUNCTIONCALL = 134, 
	CODEDOMTYPES_ZOEFORSTATEMENT = 135, 
	CODEDOMTYPES_ZOEDOCUMENTBODY = 136, 
	CODEDOMTYPES_ZOEDOCUMENTATION = 137, 
	CODEDOMTYPES_ZOEBINARYOPERATOR = 138, 
	CODEDOMTYPES_ZOECONFIG = 139, 
	CODEDOMTYPES_ZOEDECLARATORLIST = 140, 
	CODEDOMTYPES_ZOEEXTENDEDLAYERDZOEDOCUMENTCONFIG = 141, 
	CODEDOMTYPES_ZOEIMPORTPROCESSCONFIG = 142, 
	CODEDOMTYPES_ZOEEXPRESSION = 143, 
	CODEDOMTYPES_ZOEINHERIT = 144, 
	CODEDOMTYPES_ZOEINFOLAYERZOEOUTPUTMODULECONFIG = 145, 
	CODEDOMTYPES_ZOESETONERROR = 146, 
	CODEDOMTYPES_ZOEINITIALIZERLIST = 147, 
	CODEDOMTYPES_ZOEJUMP = 148, 
	CODEDOMTYPES_ZOECOPYRIGHT = 149, 
	CODEDOMTYPES_ZOENAMESPACE = 150, 
	CODEDOMTYPES_ZOENEWEXPRESSION = 151, 
	CODEDOMTYPES_ZOEFORINIT = 152, 
	CODEDOMTYPES_ZOELAYERDERRORINTERCHANGECONFIG = 153, 
	CODEDOMTYPES_ZOETRYSTATEMENT = 154, 
	CODEDOMTYPES_ZOELANGUAGE = 155, 
	CODEDOMTYPES_ZOEDOWHILESTATEMENT = 156, 
	CODEDOMTYPES_ZOEDOCUMENTDATA = 157, 
	CODEDOMTYPES_ZOEDIRECTOUTPUT = 158, 
	CODEDOMTYPES_ZOELAYERDZOEPROGRAMCONFIG = 159, 
	CODEDOMTYPES_ZOEIFSTATEMENT = 160, 
	CODEDOMTYPES_ZOEFUNCTION = 161, 
	CODEDOMTYPES_ZOEFIELD = 162, 
	CODEDOMTYPES_ZOEBASEINITIALIZERS = 163, 
	CODEDOMTYPES_ZOECLASS = 164, 
	CODEDOMTYPES_ZOEUNARYOPERATOR = 165, 
	CODEDOMTYPES_ZOELITERAL = 166, 
	CODEDOMTYPES_CLASSFACTORYDATA = 167, 
	CODEDOMTYPES_ZOEBASEINITIALIZER = 168, 
	CODEDOMTYPES_ZOEERROR = 169, 
	CODEDOMTYPES_ZOECOMPLEXFUNCTIONCALL = 170, 
	CODEDOMTYPES_ZOEGARBAGECOLLECTOR = 171, 
	CODEDOMTYPES_ZOELAYERDCOMPILER = 172, 
};
	extern const DOM_CHARP __CODEDOM_ZOEPLATFORMSUPPORTLEVEL_ENUM[];
	enum XplPlatformsupportlevel_enum{ZOEPLATFORMSUPPORTLEVEL_ENUM_COMPLETE,ZOEPLATFORMSUPPORTLEVEL_ENUM_COMPLETE_BETA,ZOEPLATFORMSUPPORTLEVEL_ENUM_COMPLETE_ALPHA,ZOEPLATFORMSUPPORTLEVEL_ENUM_INCOMPLETE,ZOEPLATFORMSUPPORTLEVEL_ENUM_INCOMPLETE_BETA,ZOEPLATFORMSUPPORTLEVEL_ENUM_INCOMPLETE_ALPHA,ZOEPLATFORMSUPPORTLEVEL_ENUM_EXPERIMENTAL,ZOEPLATFORMSUPPORTLEVEL_ENUM_EXPERIMENTAL_BETA,ZOEPLATFORMSUPPORTLEVEL_ENUM_EXPERIMENTAL_ALPHA,ZOEPLATFORMSUPPORTLEVEL_ENUM_POSSIBLY_TESTED,ZOEPLATFORMSUPPORTLEVEL_ENUM_POSSIBLY_NONTESTED,ZOEPLATFORMSUPPORTLEVEL_ENUM_EZOEICITLY_UNSUPPORTED};
	extern const DOM_CHARP __CODEDOM_ZOEDOCSOURCETYPE_ENUM[];
	enum XplDocsourcetype_enum{ZOEDOCSOURCETYPE_ENUM_XML,ZOEDOCSOURCETYPE_ENUM_HTML,ZOEDOCSOURCETYPE_ENUM_ZOE,ZOEDOCSOURCETYPE_ENUM_TEXT,ZOEDOCSOURCETYPE_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOEFACTORYTYPE_ENUM[];
	enum XplFactorytype_enum{ZOEFACTORYTYPE_ENUM_NONE,ZOEFACTORYTYPE_ENUM_INAME,ZOEFACTORYTYPE_ENUM_EXPRESSION,ZOEFACTORYTYPE_ENUM_EXPRESSIONLIST,ZOEFACTORYTYPE_ENUM_STATEMENT};
	extern const DOM_CHARP __CODEDOM_ZOEBITORDER_ENUM[];
	enum XplBitorder_enum{ZOEBITORDER_ENUM_LITTLE_ENDIAN,ZOEBITORDER_ENUM_BIG_ENDIAN,ZOEBITORDER_ENUM_IGNORE};
	extern const DOM_CHARP __CODEDOM_ZOEMEMORYMODEL_ENUM[];
	enum XplMemorymodel_enum{ZOEMEMORYMODEL_ENUM_LINEAL,ZOEMEMORYMODEL_ENUM_SEGMENTED,ZOEMEMORYMODEL_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOELITERALTYPE_ENUM[];
	enum XplLiteraltype_enum{ZOELITERALTYPE_ENUM_STRING,ZOELITERALTYPE_ENUM_ASCIISTRING,ZOELITERALTYPE_ENUM_CHAR,ZOELITERALTYPE_ENUM_ASCIICHAR,ZOELITERALTYPE_ENUM_BOOL,ZOELITERALTYPE_ENUM_INTEGER,ZOELITERALTYPE_ENUM_REAL,ZOELITERALTYPE_ENUM_FLOAT,ZOELITERALTYPE_ENUM_DOUBLE,ZOELITERALTYPE_ENUM_DECIMAL,ZOELITERALTYPE_ENUM_OCT,ZOELITERALTYPE_ENUM_HEX,ZOELITERALTYPE_ENUM_DATETIME,ZOELITERALTYPE_ENUM_UUID,ZOELITERALTYPE_ENUM_NULL,ZOELITERALTYPE_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOEDOCUMENTTYPE_ENUM[];
	enum XplDocumenttype_enum{ZOEDOCUMENTTYPE_ENUM_LAYERD_ZOE_DOC,ZOEDOCUMENTTYPE_ENUM_LAYERD_EZOE_DOC,ZOEDOCUMENTTYPE_ENUM_LAYERD_ZOE_PROG,ZOEDOCUMENTTYPE_ENUM_IMPORT_PROCESS,ZOEDOCUMENTTYPE_ENUM_INFOLDZOE_OUTPUTMODULE,ZOEDOCUMENTTYPE_ENUM_REQUIREMENTS_EZOE,ZOEDOCUMENTTYPE_ENUM_ERRORS_INTERCHANGE_DOC,ZOEDOCUMENTTYPE_ENUM_VIRTUAL_SUBPROGRAM_LAYERD_ZOE,ZOEDOCUMENTTYPE_ENUM_PARAMETER_DOCUMENT_LAYERD_ZOE};
	extern const DOM_CHARP __CODEDOM_ZOEJUMPTYPE_ENUM[];
	enum XplJumptype_enum{ZOEJUMPTYPE_ENUM_BREAK,ZOEJUMPTYPE_ENUM_CONTINUE,ZOEJUMPTYPE_ENUM_RESUME,ZOEJUMPTYPE_ENUM_RESUMENEXT,ZOEJUMPTYPE_ENUM_GOTO};
	extern const DOM_CHARP __CODEDOM_ZOEPOINTERTYPE_ENUM[];
	enum XplPointertype_enum{ZOEPOINTERTYPE_ENUM_C_NATIVE,ZOEPOINTERTYPE_ENUM_DEFAULT,ZOEPOINTERTYPE_ENUM_SAFECLASS};
	extern const DOM_CHARP __CODEDOM_ZOEUNARYOPERATORS_ENUM[];
	enum XplUnaryoperators_enum{ZOEUNARYOPERATORS_ENUM_MIN,ZOEUNARYOPERATORS_ENUM_INC,ZOEUNARYOPERATORS_ENUM_DEC,ZOEUNARYOPERATORS_ENUM_PREINC,ZOEUNARYOPERATORS_ENUM_PREDEC,ZOEUNARYOPERATORS_ENUM_IND,ZOEUNARYOPERATORS_ENUM_AOF,ZOEUNARYOPERATORS_ENUM_RAOF,ZOEUNARYOPERATORS_ENUM_SIZEOF,ZOEUNARYOPERATORS_ENUM_TYPEOF,ZOEUNARYOPERATORS_ENUM_ONECOMP,ZOEUNARYOPERATORS_ENUM_NOT};
	extern const DOM_CHARP __CODEDOM_ZOEERRORSOURCETYPE_ENUM[];
	enum XplErrorsourcetype_enum{ZOEERRORSOURCETYPE_ENUM_ZOE_DOC,ZOEERRORSOURCETYPE_ENUM_LAYERD_DOC,ZOEERRORSOURCETYPE_ENUM_OUTPUTMODULE_IMPORT,ZOEERRORSOURCETYPE_ENUM_OUTPUTMODULE_RENDER,ZOEERRORSOURCETYPE_ENUM_OUTPUTMOUDLE_COMPILE,ZOEERRORSOURCETYPE_ENUM_LAYERDZOE_EZOE_GENERATION,ZOEERRORSOURCETYPE_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOETYPENAME_ENUM[];
	enum XplTypename_enum{ZOETYPENAME_ENUM_INTEGER,ZOETYPENAME_ENUM_UNSIGNED,ZOETYPENAME_ENUM_LONG,ZOETYPENAME_ENUM_ULONG,ZOETYPENAME_ENUM_SHORT,ZOETYPENAME_ENUM_USHORT,ZOETYPENAME_ENUM_SBYTE,ZOETYPENAME_ENUM_BYTE,ZOETYPENAME_ENUM_FLOAT,ZOETYPENAME_ENUM_DOUBLE,ZOETYPENAME_ENUM_LDOUBLE,ZOETYPENAME_ENUM_DECIMAL,ZOETYPENAME_ENUM_FIXED,ZOETYPENAME_ENUM_BOOLEAN,ZOETYPENAME_ENUM_CHAR,ZOETYPENAME_ENUM_STRING,ZOETYPENAME_ENUM_ASCIICHAR,ZOETYPENAME_ENUM_ASCIISTRING,ZOETYPENAME_ENUM_DATE,ZOETYPENAME_ENUM_UUID,ZOETYPENAME_ENUM_VOID,ZOETYPENAME_ENUM_OBJECT,ZOETYPENAME_ENUM_TYPE,ZOETYPENAME_ENUM_BLOCK};
	extern const DOM_CHARP __CODEDOM_ZOEVARSTORAGE_ENUM[];
	enum XplVarstorage_enum{ZOEVARSTORAGE_ENUM_AUTO,ZOEVARSTORAGE_ENUM_STATIC,ZOEVARSTORAGE_ENUM_EXTERN,ZOEVARSTORAGE_ENUM_STATIC_EXTERN};
	extern const DOM_CHARP __CODEDOM_ZOETERNARYOPERATORS_ENUM[];
	enum XplTernaryoperators_enum{ZOETERNARYOPERATORS_ENUM_BOOLEAN,ZOETERNARYOPERATORS_ENUM_RESERVED};
	extern const DOM_CHARP __CODEDOM_ZOEACCESSTYPE_ENUM[];
	enum XplAccesstype_enum{ZOEACCESSTYPE_ENUM_INTERNAL,ZOEACCESSTYPE_ENUM_PUBLIC,ZOEACCESSTYPE_ENUM_PROTECTED,ZOEACCESSTYPE_ENUM_PRIVATE,ZOEACCESSTYPE_ENUM_IINTERNAL,ZOEACCESSTYPE_ENUM_IPUBLIC,ZOEACCESSTYPE_ENUM_IPROTECTED,ZOEACCESSTYPE_ENUM_IPRIVATE};
	extern const DOM_CHARP __CODEDOM_ZOELAYERDZOEPROGRAMMODULETYPE_ENUM[];
	enum XplLayerDZoeProgramModuletype_enum{ZOELAYERDZOEPROGRAMMODULETYPE_ENUM_EXECUTABLE,ZOELAYERDZOEPROGRAMMODULETYPE_ENUM_STATIC_LIB,ZOELAYERDZOEPROGRAMMODULETYPE_ENUM_DYNAMIC_LIB,ZOELAYERDZOEPROGRAMMODULETYPE_ENUM_SCRIPT,ZOELAYERDZOEPROGRAMMODULETYPE_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOEBINARYOPERATORS_ENUM[];
	enum XplBinaryoperators_enum{ZOEBINARYOPERATORS_ENUM_ADD,ZOEBINARYOPERATORS_ENUM_MIN,ZOEBINARYOPERATORS_ENUM_MUL,ZOEBINARYOPERATORS_ENUM_DIV,ZOEBINARYOPERATORS_ENUM_MOD,ZOEBINARYOPERATORS_ENUM_EXP,ZOEBINARYOPERATORS_ENUM_LSH,ZOEBINARYOPERATORS_ENUM_RSH,ZOEBINARYOPERATORS_ENUM_AND,ZOEBINARYOPERATORS_ENUM_OR,ZOEBINARYOPERATORS_ENUM_EQ,ZOEBINARYOPERATORS_ENUM_NOTEQ,ZOEBINARYOPERATORS_ENUM_GR,ZOEBINARYOPERATORS_ENUM_LS,ZOEBINARYOPERATORS_ENUM_GREQ,ZOEBINARYOPERATORS_ENUM_LSEQ,ZOEBINARYOPERATORS_ENUM_BAND,ZOEBINARYOPERATORS_ENUM_BOR,ZOEBINARYOPERATORS_ENUM_XOR,ZOEBINARYOPERATORS_ENUM_M,ZOEBINARYOPERATORS_ENUM_PM,ZOEBINARYOPERATORS_ENUM_MP,ZOEBINARYOPERATORS_ENUM_PMP,ZOEBINARYOPERATORS_ENUM_MS,ZOEBINARYOPERATORS_ENUM_MSM,ZOEBINARYOPERATORS_ENUM_RM,ZOEBINARYOPERATORS_ENUM_IMP};
	extern const DOM_CHARP __CODEDOM_ZOECASTTYPE_ENUM[];
	enum XplCasttype_enum{ZOECASTTYPE_ENUM_STATIC,ZOECASTTYPE_ENUM_DYNAMIC,ZOECASTTYPE_ENUM_CONST,ZOECASTTYPE_ENUM_REINTERPRET,ZOECASTTYPE_ENUM_OTHER};
	extern const DOM_CHARP __CODEDOM_ZOEPARAMETERDIRECTION_ENUM[];
	enum XplParameterdirection_enum{ZOEPARAMETERDIRECTION_ENUM_IN,ZOEPARAMETERDIRECTION_ENUM_OUT,ZOEPARAMETERDIRECTION_ENUM_INOUT};
	extern const DOM_CHARP __CODEDOM_ZOEPLATFORMMATCH_ENUM[];
	enum XplPlatformMatch_enum{ZOEPLATFORMMATCH_ENUM_LIKE,ZOEPLATFORMMATCH_ENUM_EXACTNAME,ZOEPLATFORMMATCH_ENUM_EXACTNAMEANDVERSION,ZOEPLATFORMMATCH_ENUM_LIKENAMEANDEXACTVERSION,ZOEPLATFORMMATCH_ENUM_CUSTOMMATCH};
	extern const DOM_CHARP __CODEDOM_ZOEAUTOINSTACETYPES_ENUM[];
	enum XplAutoInstaceTypes_enum{ZOEAUTOINSTACETYPES_ENUM_CALL,ZOEAUTOINSTACETYPES_ENUM_BLOCK,ZOEAUTOINSTACETYPES_ENUM_CALLTOFUNCTION,ZOEAUTOINSTACETYPES_ENUM_CLASS,ZOEAUTOINSTACETYPES_ENUM_NAMESPACE,ZOEAUTOINSTACETYPES_ENUM_VIRTUALSECTION};
	extern const DOM_CHARP __CODEDOM_ZOEASSINGOP_ENUM[];
	enum XplAssingop_enum{ZOEASSINGOP_ENUM_NONE,ZOEASSINGOP_ENUM_ADD,ZOEASSINGOP_ENUM_SUB,ZOEASSINGOP_ENUM_MUL,ZOEASSINGOP_ENUM_DIV,ZOEASSINGOP_ENUM_MOD,ZOEASSINGOP_ENUM_LSH,ZOEASSINGOP_ENUM_RSH,ZOEASSINGOP_ENUM_AND,ZOEASSINGOP_ENUM_XOR,ZOEASSINGOP_ENUM_OR};

}

#endif

